const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ctx={console};vm.createContext(ctx);
vm.runInContext(fs.readFileSync(__dirname+'/Code.template.gs','utf8'),ctx);
vm.runInContext(fs.readFileSync(__dirname+'/ecpa_course_sources.js','utf8'),ctx);
const q={course:'Test course',question:'Question?',type:'單選',options:['A','B']};
const table='<title>Test course《解答》</title><table><tr><td>Q</td><td></td><td>Question?</td></tr><tr><td></td><td></td><td>A</td></tr><tr><td>v</td><td></td><td>B</td></tr></table>';
ctx.ecpaCourseSourceUrls=()=>['https://roddayeye.pixnet.net/blog/post/1'];
ctx.ecpaFetchCoursePage=url=>({html:table,url});
ctx.ecpaReviewApi=()=>{throw Error('No API should be needed for an indexed exact answer');};
let v=ctx.ecpaVerifyCourseAnswer(q);assert.equal(v.answer,'B');assert.equal(v.method,'course_answer_exact_v1');
assert.equal(ctx.ecpaCourseSourceAllowed('https://roddayeye.pixnet.net.attacker.com/'),false);
assert.equal(ctx.ecpaCourseSourceAllowed('https://www.peigogo.com@127.0.0.1/'),false);
assert.equal(ctx.ecpaCourseSourceAllowed('https://www.peigogo.com/2024/01/test.html'),true);
ctx.ecpaReviewApi=()=>({searched:true,data:{urls:[]}});
assert.equal(ctx.ecpaVerifyCourseAnswer({...q,options:['A','C']}),null);
assert.equal(ctx.ecpaVerifyCourseAnswer({...q,question:'Question!'}),null);
assert.equal(ctx.ecpaVerifyCourseAnswer({...q,course:'Other course'}),null);
ctx.ecpaCourseSourceUrls=()=>['https://roddayeye.pixnet.net/1','https://roddayeye.pixnet.net/2'];
ctx.ecpaFetchCoursePage=url=>({url,html:url.endsWith('/2')?table.replace('<td></td><td></td><td>A','<td>v</td><td></td><td>A').replace('<td>v</td><td></td><td>B','<td></td><td></td><td>B'):table});
assert.equal(ctx.ecpaVerifyCourseAnswer(q).conflict,true);
const pei='<div class="post-body-inner"><div>問：Question?</div><div>&nbsp; A</div><div>v <span> B</span></div></div><div>Advertisement must not be an option</div>';
let rows=ctx.ecpaCoursePageRows(pei,'https://www.peigogo.com/a');assert.equal(rows.length,1);assert.equal(rows[0].answers[0],'B');assert.equal(rows[0].options.length,2);
const rodi='<table><tr><td>問</td><td>Question?</td></tr><tr><td></td><td>A</td></tr><tr><td>✓</td><td>B</td></tr></table>';
rows=ctx.ecpaCoursePageRows(rodi,'https://www.rodiyer.idv.tw/a');assert.equal(rows[0].answers[0],'B');
// Restore the actual fetcher and test redirect host validation.
vm.runInContext(fs.readFileSync(__dirname+'/ecpa_course_sources.js','utf8'),ctx);
let calls=0;ctx.UrlFetchApp={fetch:()=>{calls++;return {getResponseCode:()=>302,getAllHeaders:()=>({Location:'https://127.0.0.1/secret'})};}};
assert.equal(ctx.ecpaFetchCoursePage('https://www.peigogo.com/test'),null);assert.equal(calls,1);
console.log('PASS: three source formats, exact course/question/options, conflict retention, no API on indexed answer, redirect restrictions');
